---
name: cat_dog_classifier
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.5+3
  splashscreen: ^1.3.5
  tflite_flutter: ^0.9.0
  google_fonts: ^3.0.1
  tflite: ^1.1.2
flutter:
  uses-material-design: true

  assets:
    - assets/cat_and_dog.png